version: 2

sources:
  - name: all_checked_and_pass
    schema: analytics
    loaded_at_field: loaded_at

    freshness:
      warn_after: {count: 100, period: hour}
      error_after: {count: 100, period: hour}

    tables:
      - name: table_1
        identifier: source
        columns:
          - name: loaded_at
            tests:
              - unique

      - name: table_2
        identifier: source

      - name: table_3
        identifier: source

  - name: some_checked_and_pass
    schema: analytics
    loaded_at_field: loaded_at

    tables:
      - name: table_1
        identifier: source
        freshness:
          warn_after: {count: 100, period: hour}
          error_after: {count: 100, period: hour}

      - name: table_2
        identifier: source
        freshness:
          warn_after: {count: 100, period: hour}
          error_after: {count: 100, period: hour}

      - name: table_3
        identifier: source

  - name: some_checked_and_some_warn
    schema: analytics
    loaded_at_field: loaded_at

    tables:
      - name: table_1
        identifier: source
        freshness:
          warn_after: {count: 0, period: minute}
          error_after: {count: 100, period: hour}

      - name: table_2
        identifier: source
        freshness:
          warn_after: {count: 100, period: hour}
          error_after: {count: 100, period: hour}

      - name: table_3
        identifier: source

  - name: some_checked_and_some_fail
    schema: analytics
    loaded_at_field: loaded_at

    tables:
      - name: table_1
        identifier: source
        freshness:
          warn_after: {count: 0, period: minute}
          error_after: {count: 0, period: hour}

      - name: table_2
        identifier: source
        freshness:
          warn_after: {count: 100, period: hour}
          error_after: {count: 100, period: hour}

      - name: table_3
        identifier: source

  - name: one_of_each
    schema: analytics
    loaded_at_field: loaded_at

    tables:
      - name: table_1
        identifier: source
        freshness:
          warn_after: {count: 0, period: minute}
          error_after: {count: 0, period: hour}

      - name: table_2
        identifier: source
        freshness:
          warn_after: {count: 100, period: hour}
          error_after: {count: 100, period: hour}

      - name: table_3
        identifier: source
        freshness:
          warn_after: {count: 0, period: hour}
          error_after: {count: 100, period: hour}

      - name: table_4
        identifier: source

  - name: error_selecting_from_source_and_otherwise_ok
    schema: analytics
    loaded_at_field: loaded_at

    tables:
      - name: table_1
        identifier: source
        loaded_at_field: bad_field
        freshness:
          warn_after: {count: 0, period: minute}
          error_after: {count: 0, period: hour}

      - name: table_2
        identifier: source

      - name: table_3
        identifier: source
        freshness:
          warn_after: {count: 100, period: hour}
          error_after: {count: 100, period: hour}

  - name: error_selecting_from_source_and_fail
    schema: analytics
    loaded_at_field: loaded_at

    tables:
      - name: table_1
        identifier: source
        loaded_at_field: bad_field
        freshness:
          warn_after: {count: 100, period: minute}
          error_after: {count: 100, period: hour}

      - name: table_2
        identifier: source
        freshness:
          warn_after: {count: 0, period: hour}
          error_after: {count: 0, period: hour}

  - name: just_error_selecting_from_source
    schema: analytics
    loaded_at_field: loaded_at

    tables:
      - name: table_1
        identifier: source
        loaded_at_field: bad_field
        freshness:
          warn_after: {count: 100, period: minute}
          error_after: {count: 100, period: hour}

      - name: table_2
        identifier: source

      - name: table_3
        identifier: source
